apiVersion: v1
kind: Service
metadata:
  name: qit-admin-api
  labels:
    app: qit-admin-api
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: qit-admin-api
