apiVersion: apps/v1
kind: Deployment
metadata:
  name: qit-admin-www
  labels:
    app: qit-admin-client
spec:
  template:
    metadata:
      labels:
        app: qit-admin-client
    spec:
      containers:
        - name: qit-admin-www
          image: thejz/qit-admin-www
          imagePullPolicy: Always
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
