apiVersion: v1
kind: Service
metadata:
  name: qit-admin-www
  labels:
    app: qit-admin-client
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: qit-admin-client
